apiVersion: v1
kind: Service
metadata:
  annotations:
    api.service.kubernetes.io/path: /openshift-kie-springboot
  name: openshift-kie-springboot
  labels:
    app: openshift-kie-springboot
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: openshift-kie-springboot
