kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: openshift-kie-thorntail
  labels:
    app: openshift-kie-thorntail
subjects:
  - kind: ServiceAccount
    name: openshift-kie-thorntail
roleRef:
  kind: Role
  name: openshift-kie-thorntail
  apiGroup: rbac.authorization.k8s.io